language: python
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nosetests
cache: pip
