language: python
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
python:
  - "2.6"
  - "2.7"
# command to install dependencies
cache: pip

install:
  - pip install -e .

# command to run tests
script: nosetests

