language: python
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran
python:
  - "2.6"
  - "2.7"
# command to install dependencies
cache:
  directories:
    - $HOME/.pip-cache/

install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - python setup.py build
  - python setup.py install
# command to run tests
script: nosetests

